const wording = {
    overviewText: 'Overview',
    prerequisitesText: 'Prerequisites',
    logisticsText: 'Visa and Logistics',
    overviewHeading: 'Sustainable development goal',
    contentHeading: 'Peace Justice And Strong Institutions',
    descriptionHeading: 'Role description',
    activitiesHeading: 'Main activities',
    backgroundHeading: 'Backgrounds',
    skillsHeading: 'Skills',
    citizenHeading: 'Citizenships',
    languagesHeading: 'Languages',
    levelsHeading: 'Study Levels',
    hostOfficeHeading: 'Host AIESEC office',
    healthInsurance:'Health Insurance',
    workingHours: 'Working hours',
    logistics: 'Logistics',
    visaHeading: 'Visa',
    visaTypeHeading: 'VISA TYPE',
    visaDurationHeading: 'VISA DURATION',
    visaLinkHeading: 'VISA LINK',
    weekendOff: 'Not on weekends',
    accommodationProvidedText: 'Accommodation Provided',
    accommodationCoveredText: 'Accommodation Covered',
    foodProvidedText: 'Food Provided',
    foodCoveredText: 'Food Covered',
    languageVolunteer: 'LANGUAGE',
    earliestStartText: 'EARLIEST START DATE',
    latestEndText: 'LATEST END DATE',
    durationText: 'DURATION',
    salaryText: 'SALARY',
    positionText: 'POSITIONS',
    loginButtonText: 'Login To Apply',
  }

  export { wording }